apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1
          ports:
            - containerPort: 3001
          env:
            - name: PUID
              value: "1000" # Replace with the actual PUID if different
            - name: PGID
              value: "1000" # Replace with the actual PGID if different
            - name: TZ
              value: "America/New_York" # Replace with the actual timezone if different
          volumeMounts:
            - name: app-data
              mountPath: /app/data
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc
