apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30002 # Adjust this port as necessary within the allowed range
  selector:
    app: uptime-kuma
